import Navbar from "@/components/Navbar";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PublicLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="es">
      <body className="mx-auto max-w-md container">
        <Navbar />
        <h2 className="text-center text-sm my-4 ">Rutas públicas</h2>
        {children}
      </body>
    </html>
  );
};
export default PublicLayout;
